apiVersion: v1
kind: Service

metadata:
  name: cloud-native-service

  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"

spec:
  selector:
    app: cloud-native-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: LoadBalancer
